cat \
  src/const.js \
  src/weights.js \
  src/utils.js \
  src/node.js \
  src/iterate.js \
  src/go.js \
  src/search.js \
  src/qsearch.js \
  src/perft.js \
  src/pv.js \
  src/net.js \
  src/fen.js \
  src/board.js \
  src/makemove.js \
  src/tt.js \
  src/position.js \
  src/genmoves.js \
  src/attacks.js \
  src/eval.js \
  src/history.js \
  src/see.js \
  src/draw.js \
  src/fen.js \
  src/debug.js \
  src/tc.js \
  src/data.js \
  src/tests.js \
  src/uci.js \
  src/init.js \
  src/main.js \
    > lozza.js
  
node lozza uci # check syntax
