#!/bin/bash

if [ "$(hostname)" = "colinj" ]
then
  echo "use the epyc!"
  exit 1
fi

if command -v cpupower >/dev/null; then
  sudo cpupower frequency-set -g performance || true
fi

rm -f sprt.pgn
rm -f sprt.log

e1=./lozza
e2=./releases/lozza
#e2=./releases/lozza10-linux

elo0=0
elo1=3
concurrency=32
book=UHO_Lichess_4852_v1

if [ "$1" = "ltc" ]; then
  hash=128
  tc=100+1
  shift
else
  hash=16
  tc=10+0.1
  [ "$1" = "stc" ] && shift
fi

e1name="${e1//[.\/]/_}"
e2name="${e2//[.\/]/_}"

#CPUS=0,2,4,6,8,10   # physical cores only (no SMT) Ryzen 5000 series
CPUS=0-31   # physical cores only (no SMT) EPYC 7502P

taskset -c $CPUS \
~/chess_data/fastchess-ob -recover -concurrency $concurrency -rounds 10000 -repeat \
-resign movecount=5 score=600 \
-draw movenumber=40 movecount=8 score=5 \
-engine cmd=$e1 proto=uci tc=$tc timemargin=250 option.Hash=$hash name=$e1name \
-engine cmd=$e2 proto=uci tc=$tc timemargin=250 option.Hash=$hash name=$e2name \
-openings file=~/chess_data/$book.epd format=epd order=random -srand $RANDOM \
-sprt elo0=$elo0 elo1=$elo1 alpha=0.05 beta=0.1 \
-pgnout file=sprt.pgn 

#../chess_data/cutechess-ob -concurrency $concurrency -each tc=0/$tc \
#-sprt elo0=$elo0 elo1=$elo1 alpha=0.05 beta=0.1 \
#-engine name=$e1 proto=uci cmd=$e1 timemargin=250 option.Hash=$hash \
#-engine name=$e2 proto=uci cmd=$e2 timemargin=250 option.Hash=$hash \
#-srand $RANDOM$RANDOM -openings file=~/chess_data/$book.epd format=epd order=random \
#-repeat -games 200000 -recover -pgnout sprt.pgn fi \
#-draw movenumber=40 movecount=8 score=10 \
#-resign movecount=5 score=400 \
#-ratinginterval 10 $1
