#!/bin/bash

shebang="#!/home/xyzzy/.nvm/versions/node/v23.5.0/bin/node"

e1=lozza.js
e2=lozzacand.js

echo $e1 v $e2

grep __dirname $e1
grep __dirname $e2

echo $shebang | cat - $e1 > x$e1
echo $shebang | cat - $e2 > x$e2

chmod +x x$e1
chmod +x x$e2

rm cctry.pgn

../cutechess-ob \
-engine name=$e1 proto=uci cmd=x$e1 \
-engine name=$e2 proto=uci cmd=x$e2 \
-each tc=0/60+1 \
-srand $RANDOM$RANDOM -openings file=data/4moves_noob.epd format=epd order=random \
-repeat -games 2 -rounds 10000 \
-concurrency 12 \
-sprt elo0=0 elo1=5 alpha=0.05 beta=0.1 \
-draw movenumber=40 movecount=8 score=10 \
-resign movecount=5 score=400 twosided=true \
-maxmoves 200 -ratinginterval 10 -wait 100 -recover \
-pgnout cctry.pgn fi $1
