#!/bin/bash

../fastchess \
-engine name=coal cmd=/home/xyzzy/.nvm/versions/node/v23.5.0/bin/node args=lozza.js \
-engine name=cand cmd=/home/xyzzy/.nvm/versions/node/v23.5.0/bin/node args=lozzacand.js \
-each tc=20+0.2 \
-srand $RANDOM$RANDOM -openings file=data/4moves_noob.epd format=epd order=random \
-rounds 20000 \
-concurrency 12 \
-sprt elo0=0 elo1=5 alpha=0.05 beta=0.1 \
-draw movenumber=40 movecount=8 score=10 \
-resign movecount=5 score=400 twosided=true \
-maxmoves 200

